export const githubConfig = {
  username: `bucketio`,
  repoList: Array.from({ length: 20 }, (_, i) => `img${i}`),
  branch: `main`,
  accessTokenList: [
    `ghp_sqQg5y7XC7Fy8XdoocsmdVEYRiRiTZPvbwzTL4MRjQc`,
    `ghp_jB5JXzBjpGbgzdoocsmdogWfSHhfCKGVstozw1cAsPv`,
    `ghp_zvy8wkHo259g7doocsmdJnUKOQd1WO1SPzZ9G0O9cJD`,
    `ghp_DnCJc2Ms0RVZ1doocsmdiWOAN78FurfSeD1Pv2Y28pO`,
    `ghp_EsMYDv9WVjXWP5doocsmd1nnDml2DEP95rOiz44bSo0`,
    `ghp_L4isHf01nllOOdoocsmdHBGoDG6jscCA09WV44QDvlg`,
    `ghp_qWciwYXHPakAUGdoocsmdBOBZdRcV08JThKey3mBZNJ`,
    `ghp_rxkvIO08wVL2DMdoocsmd2jDEhcatp2rfVyhd3A7RiS`,
    `ghp_1RvkWKboSxr0yVdoocsmd7OtBCpecYwoV6deh3utifJ`,
    `ghp_cduanDnAug60ngdoocsmdF1uDstXUi6S9RMhY1qdada`,
    `ghp_q6mxuJIkqAcsCXdoocsmdkkjWvzGlMVRuy5zI0IWNDx`,
    `ghp_Pv4npPeJpChKFMTdoocsmdCQneopUcqJrqrjl3vrt9A`,
    `ghp_gKMCFqMaQiLTqhjdoocsmd7BJE8RyK6AdRw4b42CutS`,
    `ghp_2oShgb33qFlqBmadoocsmdludmuLYxBFY5bao1XrsVo`,
    `ghp_eYyd3kxWTZmsV8doocsmdDFbAa7AEGQTJgmOd0GUmtY`,
  ],
}
